import type { NextPage } from 'next'
import Head from 'next/head'

import { Landing } from './landing'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>ShonenPlays</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
    </div>
  )
}

export default Home
