import type { NextPage } from 'next'
import Head from 'next/head'

import { Landing } from '../components/landing'
import { AboutUs } from '../components/about-us'
import { Skills } from '../components/skills'
import { Projects } from '../components/projects'
import { TrustedBy } from '../components/trusted-by'
import { Testimonials } from '../components/testimonials'
import { ContactUs } from '../components/contact-us'
import { Footer } from '../components/footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>AimanCorp.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
      <AboutUs />
      <Skills />
      <Projects />
      <TrustedBy />
      {/* <Testimonials /> */}
      <ContactUs />
      <Footer />
    </div>
  )
}

export default Home
